#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper in Hyprland

WALLPAPER='/home/henry/Pictures/wallpapers/wallpaper_3.jpg'

swaybg --output '*' --mode fill --image "$WALLPAPER"
